spring.datasource.url=jdbc:mysql://mysql:3306/identity_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret.key=o7Y2Bx2tWnOgOhAkbUTs4Spc5YjTOLujUeENqoFuqfK