version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: identity-mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_db
    ports:
      - "3306:3306"

  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    container_name: identity-service
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy